# Generated by Django 5.0.1 on 2024-02-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('ordinal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('url', models.URLField()),
                ('ordinal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Место работы')),
                ('spec', models.CharField(max_length=255, verbose_name='Должность')),
                ('years', models.CharField(max_length=25)),
                ('description', models.TextField(verbose_name='Обязанности')),
                ('progress', models.TextField(verbose_name='Достижения')),
                ('doc', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файлы')),
                ('begin', models.DateField(blank=True, verbose_name='Начало работы')),
                ('finish', models.DateField(blank=True, verbose_name='Конец работы')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('ordinal', models.IntegerField()),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.category', verbose_name='Категории')),
            ],
        ),
    ]
