# Generated by Django 5.0.2 on 2024-02-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_place_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='Подробно'),
        ),
    ]
