# Generated by Django 5.0.2 on 2024-02-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_place_detail_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.TextField(verbose_name='Статья'),
        ),
    ]
