# Generated by Django 5.0.2 on 2024-03-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfolio_description_alter_portfolio_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='begin',
            field=models.DateField(blank=True, null=True, verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='place',
            name='finish',
            field=models.DateField(blank=True, null=True, verbose_name='Конец работы'),
        ),
    ]
