# Generated by Django 5.0.2 on 2024-03-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_place_begin_alter_place_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='years',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
