# Generated by Django 5.0.2 on 2024-04-07 02:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_portfolio_description_alter_portfolio_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='title',
            new_name='progress',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ordinal',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
