# Generated by Django 5.0.2 on 2024-04-07 06:03

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_title_portfolio_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
    ]
