# Generated by Django 5.0.2 on 2024-04-07 06:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_portfolio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='progress',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Достижение'),
        ),
    ]
