# Generated by Django 5.0.2 on 2024-08-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_portfolio_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='location',
            field=models.CharField(default='test', max_length=255, verbose_name='Место работы'),
            preserve_default=False,
        ),
    ]
