# Generated by Django 5.0.2 on 2024-08-10 06:20

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_portfolio_begin_portfolio_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Файлы'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='responsibilities',
            field=django_ckeditor_5.fields.CKEditor5Field(default='test3', verbose_name='Обязанности'),
            preserve_default=False,
        ),
    ]
