# Generated by Django 5.0.2 on 2024-08-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_portfolio_doc_portfolio_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='is_published',
        ),
    ]
