# Generated by Django 5.0.2 on 2024-08-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_portfolio_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='responsibilities',
            field=models.CharField(max_length=500, verbose_name='Место работы'),
        ),
    ]
