# Generated by Django 5.0.2 on 2024-08-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_portfolio_responsibilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='url',
        ),
    ]
