# Generated by Django 5.0.2 on 2024-08-10 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_remove_portfolio_doc_remove_portfolio_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.category', verbose_name='Категории'),
        ),
    ]
