# Generated by Django 5.0.2 on 2024-08-10 13:28

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_portfolio_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='responsibilities',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Обязанности'),
        ),
    ]
