# Generated by Django 5.0.2 on 2024-08-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_portfolio_cat_alter_portfolio_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='progress',
            field=models.CharField(max_length=500, verbose_name='Достижения'),
        ),
    ]
